import { defineConfig } from "tsup";

export default defineConfig((options) => ({
  entryPoints: [
    "src/button.tsx",
    "src/divider.tsx",
    "src/icon-button.tsx",
    "src/badge.tsx",
    "src/text.tsx",
    "src/link.tsx",
    "src/checkbox.tsx",
    "src/chip.tsx",
    "src/avatar.tsx",
    "src/skeleton.tsx",
    "src/spinner.tsx",
    "src/text-input.tsx",
    "src/switch.tsx",
    "src/radio.tsx",
    "src/progress.tsx",
    "src/tooltip.tsx",
    "src/card.tsx",
    "src/dialog.tsx",
    "src/dropdown-menu.tsx",
    "src/toast.tsx",
    "src/tabs.tsx",
    "src/label.tsx",
    "src/icon.tsx",
    "src/textarea.tsx",
    "src/slider.tsx",
    "src/image.tsx",
    "src/select.tsx",
    "src/input-button.tsx",
    "src/input-otp.tsx",
    "src/chart.tsx",
    "src/foundation/index.ts",
  ],
  format: ["cjs", "esm"],
  dts: true,
  external: ["react", "react-dom", "recharts"],
  ...options,
}));
