import { defineConfig } from "tsup";

const allEntries = [
	"src/button.tsx",
	"src/divider.tsx",
	"src/icon-button.tsx",
	"src/badge.tsx",
	"src/text.tsx",
	"src/link.tsx",
	"src/checkbox.tsx",
	"src/chip.tsx",
	"src/avatar.tsx",
	"src/skeleton.tsx",
	"src/spinner.tsx",
	"src/switch.tsx",
	"src/radio.tsx",
	"src/progress.tsx",
	"src/tooltip.tsx",
	"src/card.tsx",
	"src/empty.tsx",
	"src/table.tsx",
	"src/pagination.tsx",
	"src/data-table.tsx",
	"src/drawer.tsx",
	"src/dialog.tsx",
	"src/dropdown-menu.tsx",
	"src/toast.tsx",
	"src/tabs.tsx",
	"src/label.tsx",
	"src/icon.tsx",
	"src/textarea.tsx",
	"src/slider.tsx",
	"src/image.tsx",
	"src/select.tsx",
	"src/input.tsx",
	"src/input-button.tsx",
	"src/input-otp.tsx",
	"src/toggle-group.tsx",
	"src/popover.tsx",
	"src/command.tsx",
	"src/combobox.tsx",
	"src/chart.tsx",
	"src/form.tsx",
	"src/collapsible.tsx",
	"src/carousel.tsx",
	"src/password-strength.tsx",
	"src/foundation/index.ts",
	"src/foundation/theme.css",
	"src/lib/utils.ts",
];

export default defineConfig((options) => ({
	entryPoints: allEntries,
	format: ["cjs", "esm"],
	dts: { entry: allEntries.filter((e) => !e.endsWith(".css")) },
	loader: {
		".css": "copy",
	},
	external: ["react", "react-dom", "recharts"],
	...options,
}));
